# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-full
# Command to start on workspace startup (optional)
tasks:
  - init: cd frontend && npm install
    command: cd frontend && npm run dev-server
  - init: pip3 install - requirements.txt
    command: python3 manage.py runserver 0.0.0.0:9000

# Ports to expose on workspace startup (optional)
ports:
  - port: 9000
  - port: 8080